question_repo/apps/accounts/urls.py
from django.conf.urls import url,include
from django.views.generic import TemplateView
from . import views
#CBV => class base view
#FBV => function base view
urlpatterns = [
    #TemplateView可以不写视图函数
    # url(r'^register/$', TemplateView.as_view(template_name="accounts/register.html"), name="register"),
    # 注册
    url(r'register/$', views.Register.as_view(), name="register"),
    # 登录
    url(r'^login/$', views.Login.as_view(), name='login'),
    # url(r'login/$', views.test, name="login"),
    # 退出
    url(r'logout/$', views.logout, name="logout"),
    # 忘记密码
    url(r'password/forget/$', views.test, name="password_forget"),
    # 重置密码
    url(r'password/reset/token/$', views.test, name="password_reset"),
]

question_repo/apps/apis/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^mobile_captcha/$',views.mobile_captcha,name='mobile_captcha'),
    url(r'^get_captcha/$', views.get_captcha, name='get_captcha'),
    url(r'^check_captcha/$', views.check_captcha, name='check_captcha'),
    url(r'^questions/$', views.QuestionsView.as_view(), name='questions'),
    url(r'^question/collection/(?P<id>\d+)/$', views.QuestionCollectionView.as_view(), name='question_collection'),
    url(r'^answer/collection/(?P<id>\d+)/$', views.AnswerCollectionView.as_view(), name='answer_collection'),
    url(r'^answer/(?P<id>\d+)/$', views.AnswerView.as_view(), name="answer"),
    url(r'^other_answer/(?P<id>\d+)/$', views.OtherAnswerView.as_view(), name="other_answer"),
    # url(r'^answer/collection/(?P<id>\d+)/$', views.AnswerCollectionView.as_view(), name='answer_collection'),
    url(r'^change_avator/$', views.ChangeAvator.as_view(), name='change_avator'),
]

question_repo/apps/repo/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
    url(r'^$', views.index, name='index'),
    #题目列表/贡献题目
    # url(r'^questions/$', TemplateView.as_view(template_name="questions.html"), name="questions"),
    url(r'^questions/$', views.QuestionsList.as_view(),name="questions"),
    # 贡献题目
    # url(r'^questions/$', views.Question.as_view(), name="questions"),
    #题目详情， 捕获了一个参数
    # url(r'^question/id/$', TemplateView.as_view(template_name="question_detail(app01).html"),name="question_detail"),
    url(r'^questions/(?P<id>\d+)/$', views.QuestionDetail.as_view(), name="question_detail"),

]

question_repo/question_repo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views
from django.views.static import serve
from .settings import MEDIA_ROOT
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logtest/$', views.logtest, name="logtest"),
    url(r'^accounts/', include('apps.accounts.urls', namespace="accounts")),
    url(r'^apis/', include('apps.apis.urls', namespace="apis")),
    url(r'^uc/', include('apps.usercenter.urls', namespace="uc")),
    # url(r'^apis/', include('apps.apis.urls', namespace="apis"))
    # meida 处理
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('apps.repo.urls', namespace="repo")),
]

question_repo/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from easy_thumbnails.fields import ThumbnailerImageField
from django.db.models.fields.files import ImageFieldFile
from question_repo.settings import MEDIA_ROOT,THUMB_SIZE
from .libs_images import make_thumb
import os
# Create your models here.
#继承自AbstractUser
class User(AbstractUser):
    #CharField => max_length
    #ImageField => Pillow 库
    realname = models.CharField(max_length=8, verbose_name="真实姓名")
    mobile = models.CharField(max_length=11, verbose_name="手机号")
    qq = models.CharField(max_length=11, verbose_name="QQ号")
    avator_sor = ThumbnailerImageField(upload_to="avator/%Y%m%d/", default="avator/default.jpg", verbose_name="头像")
    avator_sm = models.ImageField("头像缩略图", upload_to="avator/%Y%m%d/", default='avator/default.70x70.jpg')

    def save(self, *args, **kwargs):
        # 将上传的图片先保存
        super().save()
        # 　如果是默认图片不压缩
        if self.avator_sor.name == 'avator/default.jpg':
            return
        # 如果文件不存在，不压缩
        if not os.path.exists(os.path.join(MEDIA_ROOT, self.avator_sor.name)):
            return

        base, ext = os.path.splitext(self.avator_sor.name)
        # 从头像中生成缩略图
        thumb_pixbuf = make_thumb(os.path.join(MEDIA_ROOT, self.avator_sor.name), size=THUMB_SIZE)

        if thumb_pixbuf:
            # 缩略图的保存文件全路径=> 保存文件
            thumb_path = os.path.join(MEDIA_ROOT, base + f'.{THUMB_SIZE}x{THUMB_SIZE}' + ext)
            # 缩略图相对路径 => 数据库(以下两种取相对路径都可)
            relate_thumb_path = os.path.join('/'.join(self.avator_sor.name.split('/')[:-1]),
                                             os.path.basename(thumb_path))
            relate_thumb_path = base + f'.{THUMB_SIZE}x{THUMB_SIZE}' + ext
            # 保存缩略图
            thumb_pixbuf.save(thumb_path)
            # 保存字段值
            self.avator_sm = ImageFieldFile(self, self.avator_sm, relate_thumb_path)
            super().save()  # 再保存一下，包括缩略图等

question_repo/apps/accounts/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from .models import User
from django.contrib.auth.hashers import check_password as auth_check_password

# 用户注册
class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(label="密 码2",
                                widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请再输入密码"}))
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "error_messages": {"invalid": "验证码错误"}}))

    class Meta:
        model = User
        fields = ['username', 'mobile', 'password']
        widgets = {
            'username': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
            'mobile': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入手机号"}),
            'password': widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}),
        }

    # username是否重复django会自动检查，因为它是unique的，所以不需要自己写clean_username

    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")

    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")


#用户登录表单
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length="24",
                               widget=widgets.TextInput(attrs={"class": "form-control", "placeholder": "用户名"}))
    captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "onblur": "check_captcha()",
               "error_messages": {"invalid": "验证码错误"}}))
    password = forms.CharField(label="密 码",
                               widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))

    def check_password(self):
        print('check password')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = User.objects.get(username=username)
            return user, auth_check_password(password, user.password)
        except:
            return None, False

    def clean_username(self):
        print('hahaha')
        print(self.cleaned_data.get("username"))
        ret = User.objects.filter(username=self.cleaned_data.get("username"))
        if ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名或密码不正确")

question_repo/apps/accounts/views.py
from django.shortcuts import render,redirect,reverse
from django.shortcuts import HttpResponse
from django.core.cache import cache
from django.contrib.auth.hashers import make_password
from django.contrib import auth
from django.http import JsonResponse
import logging
from .models import User
logger = logging.getLogger('accounts')
from django.views.generic import View
from .forms import RegisterForm, LoginForm

# Create your views here.
def test(request):
    return HttpResponse("账户视图")

class Register(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "accounts/register.html", {"form":form})
        # Ajax提交表单

    def post(self, request):
        from django.core.cache import cache
        ret = {"status": 400, "msg": "调用方式错误"}
        if request.is_ajax():
            form = RegisterForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data["username"]
                password = form.cleaned_data["password"]
                mobile = form.cleaned_data["mobile"]
                mobile_captcha = form.cleaned_data["mobile_captcha"]
                mobile_captcha_reids = cache.get(mobile)
                if mobile_captcha == mobile_captcha_reids:
                    user = User.objects.create(username=username, password=make_password(password))
                    user.save()
                    ret['status'] = 200
                    ret['msg'] = "注册成功"
                    logger.debug(f"新用户{user}注册成功！")
                    user = auth.authenticate(username=username, password=password)
                    if user is not None and user.is_active:
                        auth.login(request, user)
                        logger.debug(f"新用户{user}登录成功")
                    else:
                        logger.error(f"新用户{user}登录失败")
                else:
                    # 验证码错误
                    ret['status'] = 401
                    ret['msg'] = "验证码错误或过期"
            else:
                ret['status'] = 402
                ret['msg'] = form.errors
        logger.debug(f"用户注册结果：{ret}")
        return JsonResponse(ret)


class Login(View):
    def get(self, request):
        # 设置下一跳转地址（如果get有next，如果没有跳转到repo：index
        request.session["next"] = request.GET.get('next', reverse('repo:index'))
        #如果已登录，则直接跳转到index页面
        #request.user 表示的是当前登录的用户对象，没有登录‘匿名用户’
        if request.user.is_authenticated:
            return redirect(reverse('repo:index'))
        form = LoginForm()
        return render(request, "accounts/login.html", {"form":form})

    # Form表单直接提交
    def post(self, request):
        # 表单数据绑定
        # form = LoginForm(request.POST)
        # if form.is_valid():
        #     username = form.cleaned_data["username"]
        #     user, flag = form.check_password()
        #     # user = auth.authenticate(username=username, password=password)
        #     if user is not None and user.is_active:
        #         auth.login(request, user)
        #         logger.info(f"{user.username}登录成功")
        #         # 跳转到next
        #         return redirect(request.session.get("next", '/'))
        #     msg = "用户名或密码错误"
        #     logger.error(f"{username}登录失败, 用户名或密码错误")
        # else:
        #     msg = "表单数据不完整"
        #     logger.error(form.errors)
        #     logger.error(msg)
        # return render(request, "accounts/login.html", {"form": form, "msg": msg})
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            captcha = form.cleaned_data["captcha"]
            session_captcha_code = request.session.get("captcha_code", "")
            logger.debug(f"登录提交验证码:{captcha}-{session_captcha_code}")
            # 验证码一致
            if captcha.lower() == session_captcha_code.lower():
                user, flag = form.check_password()
                # user = auth.authenticate(username=username, password=password)
                if flag and user  and user.is_active:
                    auth.login(request, user)
                    logger.info(f"{user.username}登录成功")
                    # 跳转到next
                    return redirect(request.session.get("next", '/'))
                msg = "用户名或密码错误"
                logger.error(f"{username}登录失败, 用户名或密码错误")
            else:
                msg = "验证码错误"
                logger.error(f"{username}登录失败, 验证码错误")
        else:
            msg = "表单数据不完整"
            logger.error(msg)
        return render(request, "accounts/login.html", {"form": form, "msg": msg})

def logout(request):
    auth.logout(request)
    return redirect(reverse("repo:index"))
    # return render(request, "accounts/login.html")

question_repo/apps/accounts/templates/accounts/crontribute_modal.html
{# My Modal 模态框 #}
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal-1" class="modal fade">
<div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
          <h4 class="modal-title">贡献题目</h4>
      </div>
      <div class="modal-body">
          <form class="form-horizontal" role="form" method="post" action="/question/">
              <div class="form-group">
                  <label for="inputQuestionTitle" class="col-lg-2 control-label">标题</label>
                  <div class="col-lg-10">
                      <input type="text" class="form-control" id="inputQuestionTitle" name="title" placeholder="标题">
                  </div>
              </div>
               <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">分类</label>
                    <div class="col-lg-10">
                        <select class="form-control" id="分类" name="category">
                            <option value="0"> 选择分类 </option>
                                <option value="{{ item.id }}">{{ item.name }}</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">内容</label>
                    <div class="col-lg-10">
                        <textarea type="text" class="form-control" id="inputQuestionTitle" name="content" placeholder="内容"></textarea>
                    </div>
                </div>
              <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                      <button type="submit" class="btn btn-default">提交</button>
                  </div>
              </div>
          </form>
      </div>
  </div>
</div>
</div>

question_repo/apps/accounts/templates/accounts/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户登录-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
          <form class="form-signin" method="post">
              {% csrf_token %}
            <h2 class="form-signin-heading">登录</h2>
            <div class="login-wrap">
                {{ form.username }}
                {{ form.password }}
                {{ form.captcha }}
                <a href="javascript:void(0);"><img id="captcha_img" src="data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAAeCAIAAABoq03CAAACcUlEQVR4nO1aQXLCMAxcMX1A4cwM
    Fz7QQzu8hA8wPKIz/QB/gFM/U9pLf1J+oB4MxrHl2I4dJzDscCAeSZbWliInIWbGBURkXnYAEQHI
    NHKXyGX2gUhMhnYgAJUidwCB6FKxFbFzNwknEH03sflQM0uISE33qNGV8BSUaF//Ua1Tt56n705J
    9XJl+rkOKBVYfktaB7KXkd7nBFktUYgI4IvZUlaTIZcOFWd7TuVvpaB68aQmGozrLmTVzNbMudR2
    HkNpST6wiJHrJqY4mLmDZe1PZY5bXE0mWnS913g6GGfmnm4ewXl9Foodwa3AiGBN9/5uj7jC6o+r
    61NRv/ncHLfQEP74SA6kFPqqtipCy7bvXqSFdV1y1ZvbhAH50tNEYaijmY4ofGAJmmgR0X1V0Bhw
    rsUGoXZ11mvADMuyFrS8qt9mWA7o/1FEi5y2s7xYYLlkRZ2pJNYvZiYSik8KZHf0YGbrEq/uleR0
    xPnNwCuwbyrK96jjkV1HfK4B8o+ZPz+9KoPDezLsvHQXXQbegB+OSOTUgp66O5XK8zNOpzTFgphA
    uFNfbywugha1GPN3sEabKyou7molaqUWFgA9shyzLycwCIVBkw/xjJvY76/UrNcNa+2KX1+uA+cd
    fTgAwN9fVEfY6yPoGDbkProDlU6HoMdBhO32OjKbCerbrWjTNxcAbDYAMJ1eqRex2xVoPPLPvWN5
    xmiV6d9fvLw0RkR5Ey2SzEM+Tjq7MRKibxrucxW3I5RfztZ/95wzo6Vb33m30rrbV3452/c2d7lw
    Z4zn6yaS8lE6gCofWD2IroSxf6nUjhv6jum2ic5Px2pL9Q+TVYba1BF5qAAAAABJRU5ErkJggg==
    " alt=""></a>
                <div class="user-reg">
                    <a href="#"> 用户注册</a>
                    <span class="pull-right"> <a href=""> 忘记密码?</a></span>
                </div>
                <button class="btn btn-lg btn-login btn-block" type="submit">登录</button>
                <p class="msg">alert:msg</p>
            </div>
          </form>
        </div>
    <script>
            get_captcha_img();
            $("#captcha_img").click(get_captcha_img);

            function get_captcha_img() {
                $.ajax({
                    url: '{% url 'apis:get_captcha' %}',
                    type: 'GET',
                    dataType: 'text',
                    success: function (data) {
                        $('#captcha_img').attr('src', data);
                    }
                });
            }
        // 这里在form中定义了，如果没定义可以用jquery添加事件
    // $("#id_captcha").blur(check_captcha);

    // 当失去焦点时检查验证码
            function check_captcha() {
                var captcha_code = $('#id_captcha').val();
                if (captcha_code.length == 0){
                    return false
                }
                $.ajax({
                    url: '{% url 'apis:check_captcha' %}',
                    type: 'GET',
                    dataType: 'json',
                    data: {"captcha_code": captcha_code},
                    success: function (data) {
                        if(data.code == 400){
                             $('.msg').html("验证码错误");
                        }else{
                            $('.msg').html("");
                        }
                    }
                });
            };
    </script>
    </body>
</html>

question_repo/apps/accounts/templates/accounts/login_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <form class="form-signin" action="{% url "accounts:login" %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">登录</h2>
        <div class="login-wrap">
            {{ form.username}}
            {{ form.password}}
            {{ form.captcha}}
            <a href="javascript:void(0);"><img id="captcha_img" src="#" /></a>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> 记住密码
                <span class="pull-right"> <a href="#"> 忘记密码?</a></span>
            </label>
            <button class="btn btn-lg btn-login btn-block" type="submit">登录</button>
            <p class="msg"></p>
            {% if msg %}
            <div class="alert alert-block alert-danger fade in">
                  <button data-dismiss="alert" class="close close-sm" type="button">
                      <i class="icon-remove"></i>
                  </button>
                  <strong>提醒!</strong> {{ msg }}
            </div>
            {% endif %}
        </div>
  </form>
</body>
</html>

question_repo/apps/accounts/templates/accounts/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户注册-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
    {# 加载提示工具对应的js和css #}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/gritter/css/jquery.gritter.css' %}" />
    <script type="text/javascript" src="{% static 'assets/gritter/js/jquery.gritter.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
            <form class="form-signin" id="register_form">
              {% csrf_token %}
              <h2 class="form-signin-heading">用户注册</h2>
              <div class="login-wrap">
                  {{ form.username }}
                  {{ form.password }}
                  {{ form.password2 }}
                  {{ form.mobile }}
                  {{ form.mobile_captcha }}
                  {# 给发送短信按钮添加动作 #}
                  <input onclick="sendmessage(this,60);" type="button" value="发送短信"  class="btn btn-info" style="height:38px;width: 125px;"/>
                  <button class="btn btn-lg btn-login btn-block" type="button" id="register_btn">注册</button>
                  <label class="checkbox">
                      <span class="pull-right"> 已有帐号， <a href="{% url 'accounts:login' %}"> 请登录 </a></span>
                  </label>
                  <div class="alert alert-block alert-danger fade in">
                        <button data-dismiss="alert" class="close close-sm" type="button">
                            <i class="icon-remove"></i>
                        </button>
                        <strong>提醒!</strong> 错误提示信息~~
                  </div>
              </div>
            </form>
        </div>
    {# 添加js动作#}
    <script>
        {# 发送短信验证码 #}
        function sendmessage(obj,second){
            var telRegex = /(13|14|15|17|18)\d{9}/;
            if(telRegex.test($.trim($("#id_mobile").val()))){
                $.ajax({
                    url: "{% url 'apis:mobile_captcha' %}",
                    type: "GET",
                    dataType: "json",
                    data: {"mobile": $("#id_mobile").val()},
                    success: function (data) {
                         $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '提交结果',
                            // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                            text: data.msg
                        });
                    }
                });
                countDown(obj,second)
            } else{
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: '提交结果',
                    // (string | mandatory) the text inside the notification
                    //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                    text: '手机号有误'
                });
            }
        }

        {# 重新发送倒计时 #}
        function countDown(obj,second){
        // 如果秒数还是大于0，则表示倒计时还没结束
         if(second>=0){
              // 获取默认按钮上的文字
              if(typeof buttonDefaultValue === 'undefined' ){
                buttonDefaultValue =  obj.defaultValue;
            }
            // 按钮置为不可点击状态
            obj.disabled = true;
            // 按钮里的内容呈现倒计时状态
            obj.value = buttonDefaultValue+'('+second+')';
            // 时间减一
            second--;
            // 一秒后重复执行
            setTimeout(function(){countDown(obj,second);},1000);
            // 否则，按钮重置为初始状态
            }else{
            // 按钮置未可点击状态
            obj.disabled = false;
            // 按钮里的内容恢复初始状态
            obj.value = buttonDefaultValue;
           }
        }
        $("#register_btn").click(function () {
              // some_check
              $.ajax({
                  url: "{% url 'accounts:register' %}",
                  type: "POST",
                  dataType: "json",
                  {#  register_form  =>  {"username":'cali'}#}
                  data: $("#register_form").serialize(),
                  success: function (data) {
                      if(data.status == 200 ){
                          window.location.href='{% url 'repo:index' %}';
                      }else{
                          msg = "新错误类型"
                          if(data.status == 400 || data.status == 401){
                              msg = data.msg
                          }else{
                              for(var i in data.msg){
                                  msg = i+data.msg[i]
                                  break
                              }
                          }
                           $.gritter.add({
                              // (string | mandatory) the heading of the notification
                              title: '提交结果',
                              // (string | mandatory) the text inside the notification
                              //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                              text: msg
                          });
                       }
                  },
                  // 解决csrftoken
                  beforeSend: function(xhr, settings) {
                      xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                  }
              });
          });
    </script>
    </body>
</html>