question_repo/apps/apis/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^mobile_captcha/$',views.mobile_captcha,name='mobile_captcha'),
    url(r'^get_captcha/$', views.get_captcha, name='get_captcha'),
    url(r'^check_captcha/$', views.check_captcha, name='check_captcha'),
    url(r'^questions/$', views.QuestionsView.as_view(), name='questions'),
    url(r'^question/collection/(?P<id>\d+)/$', views.QuestionCollectionView.as_view(), name='question_collection'),
    url(r'^answer/collection/(?P<id>\d+)/$', views.AnswerCollectionView.as_view(), name='answer_collection'),
    url(r'^answer/(?P<id>\d+)/$', views.AnswerView.as_view(), name="answer"),
    url(r'^other_answer/(?P<id>\d+)/$', views.OtherAnswerView.as_view(), name="other_answer"),
    # url(r'^answer/collection/(?P<id>\d+)/$', views.AnswerCollectionView.as_view(), name='answer_collection'),
    url(r'^change_avator/$', views.ChangeAvator.as_view(), name='change_avator'),
]

question_repo/apps/repo/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
    url(r'^$', views.index, name='index'),
    #题目列表/贡献题目
    # url(r'^questions/$', TemplateView.as_view(template_name="questions.html"), name="questions"),
    url(r'^questions/$', views.QuestionsList.as_view(),name="questions"),
    # 贡献题目
    # url(r'^questions/$', views.Question.as_view(), name="questions"),
    #题目详情， 捕获了一个参数
    # url(r'^question/id/$', TemplateView.as_view(template_name="question_detail(app01).html"),name="question_detail"),
    url(r'^questions/(?P<id>\d+)/$', views.QuestionDetail.as_view(), name="question_detail"),

]

question_repo/apps/usercenter/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        #个人资料
        url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
        #修改密码
        url(r'^change_passwd/$', views.ChangePasswdView.as_view(), name="change_passwd"),
        #我的回答
        url(r'^answer/$', views.AnswerView.as_view(), name='answer'),
        #我的收藏
        url(r'^collect/$', views.test, name='collect'),
        #我的贡献
        url(r'^contribut/$', views.test, name='contribut'),
        #待审题目/审核题目
        url(r'^approval/$', views.ApprovalView.as_view(), name='approval'),
        #审核题目
        url(r'^approval/(?P<id>\d+)/$', views.ApprovalPassView.as_view(), name='approval_pass'),
    ]

question_repo/question_repo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views
from django.views.static import serve
from .settings import MEDIA_ROOT
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logtest/$', views.logtest, name="logtest"),
    url(r'^accounts/', include('apps.accounts.urls', namespace="accounts")),
    url(r'^apis/', include('apps.apis.urls', namespace="apis")),
    url(r'^uc/', include('apps.usercenter.urls', namespace="uc")),
    # url(r'^apis/', include('apps.apis.urls', namespace="apis"))
    # meida 处理
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('apps.repo.urls', namespace="repo")),
]

question_repo/apps/accounts/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from .models import User
from django.contrib.auth.hashers import check_password as auth_check_password

# 用户注册
class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(label="密 码2",
                                widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请再输入密码"}))
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "error_messages": {"invalid": "验证码错误"}}))

    class Meta:
        model = User
        fields = ['username', 'mobile', 'password']
        widgets = {
            'username': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
            'mobile': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入手机号"}),
            'password': widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}),
        }

    # username是否重复django会自动检查，因为它是unique的，所以不需要自己写clean_username

    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")

    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")


#用户登录表单
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length="24",
                               widget=widgets.TextInput(attrs={"class": "form-control", "placeholder": "用户名"}))
    captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "onblur": "check_captcha()",
               "error_messages": {"invalid": "验证码错误"}}))
    password = forms.CharField(label="密 码",
                               widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))

    def check_password(self):
        print('check password')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = User.objects.get(username=username)
            return user, auth_check_password(password, user.password)
        except:
            return None, False

    def clean_username(self):
        print('hahaha')
        print(self.cleaned_data.get("username"))
        ret = User.objects.filter(username=self.cleaned_data.get("username"))
        if ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名或密码不正确")

question_repo/templates/base.html
{% load staticfiles %}
{% load thumbnail %}
<!DOCTYPE html>
<html style="overflow: hidden;" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/img/favicon.html">
    <title>{% block title %}BASE{% endblock %}-题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    {% block load_css %}
    {% endblock %}
    <style>
      body{
          font-size: 14px; !important;
      }
    </style>
</head>
<body>
    <div class="container">
        <section id="container" class="">
          <!--header start-->
          <header class="header white-bg">
              <!--logo start-->
              <a href="#" class="logo">三创<span>题库</span></a>
              <!--logo end-->
              <div class="top-nav">
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <ul class="nav navbar-nav">
                    <li class="active">
                      <a class="" href="{% url 'repo:index' %}">
                          <span> 首页 </span>
                      </a>
                    </li>
                    <li class="">
                        <a class="" href="{% url 'repo:questions' %}">
                      <span> 校招题 </span>
                    </a>
                    </li>
                  </ul>
                  <ul class="nav pull-right top-menu">
                      <li>
                          <form action="{% url 'repo:questions' %}">
                             <input type="text" class="form-control search" placeholder="Search" name="search" id="search" value="{{ search_key }}">
                          </form>
                      </li>
                      <!-- user login dropdown start-->

                      <li class="dropdown">
                          <a data-toggle="dropdown" class="dropdown-toggle" href="#" >
                              <img class="avatar" src="{{ user.avator_sor|thumbnail_url:'avatar'}}" alt="图片不存在" height="30px">
                              <span class="username">{{ user }}</span>
                              <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu">
                              <div class="log-arrow-up"></div>
                              <li><a class="" href="http://127.0.0.1:8000/uc/profile/"> 个人资料 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/change_passwd/"> 修改密码 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/answer/"> 我的回答 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/collect/"> 我的收藏 </a></li>
                              <li><a class="" href="#myModal-1" data-toggle="modal"> 贡献题目 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/contribut/"> 我的贡献 </a></li>
{#                              <li><a class="" href="http://127.0.0.1:8000/uc/approval/">待审核题目</a></li>#}
                              <li><a class="" href="http://127.0.0.1:8000/accounts/logout/"> 退出 </a></li>
                          </ul>
                      </li>

                      <!-- user login dropdown end -->
                  </ul>
              </div>
          </header>
          <!--header end-->
          <!--main content start-->
          <section id="main-content">
              <section class="wrapper">
                <!-- page start-->
                <div class="row">
                    {% block content %}这是BASE页面{% endblock %}
                </div>
                <!-- page end-->
              </section>
          </section>
          <!--main content end-->
          </section>
    </div>
    {% include 'crontribute_modal.html' %}
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <!--common script for all pages-->
    <script src="{% static 'js/common-scripts.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}" ></script>
    {% block load_js %}
    {% endblock %}
    <script>
      //owl carousel
      $(document).ready(function() {
          $("#owl-demo").owlCarousel({
              navigation : true,
              slideSpeed : 300,
              paginationSpeed : 400,
              singleItem : true
          });
      });
    </script>
</body>
</html>

question_repo/templates/crontribute_modal.html
{# My Modal 模态框 #}
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal-1" class="modal fade">
<div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
          <h4 class="modal-title">贡献题目</h4>
      </div>
      <div class="modal-body">
          <form class="form-horizontal" role="form" method="post" action="{% url 'repo:questions' %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="inputQuestionTitle" class="col-lg-2 control-label">标题</label>
                  <div class="col-lg-10">
                      <input type="text" class="form-control" id="inputQuestionTitle" name="title" placeholder="标题">
                  </div>
              </div>
               <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">分类</label>
                    <div class="col-lg-10">
                        <select class="form-control" id="分类" name="category">
                            <option value="0"> 选择分类 </option>
                                <option value="{{ item.id }}">{{ item.name }}</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">内容</label>
                    <div class="col-lg-10">
                        <textarea type="text" class="form-control" id="inputQuestionTitle" name="content" placeholder="内容"></textarea>
                    </div>
                </div>
              <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                      <button type="submit" class="btn btn-default">提交</button>
                  </div>
              </div>
          </form>
      </div>
  </div>
</div>
</div>

question_repo/templates/index.html
{% extends './base.html' %}
{% load staticfiles %}

{% block title %}首页{% endblock %}

{% block content %}
<aside class="profile-info col-lg-9">
    <!--features carousel start-->
    <section class="panel">
          <div class="flat-carousal">
              <div id="owl-demo" class="owl-carousel owl-theme" style="opacity: 1; display: block;">
                  <div class="owl-wrapper-outer">
                      <div class="owl-wrapper" style="width: 4926px; left: 0px; display: block;">
                          <div class="owl-item active" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告1</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                          <div class="owl-item" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告2</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                          <div class="owl-item" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告3</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>

                  <div class="owl-controls clickable">
                      <div class="owl-pagination">
                          <div class="owl-page active"><span class=""></span></div>
                          <div class="owl-page"><span class=""></span></div>
                          <div class="owl-page"><span class=""></span></div>
                      </div>
                      <div class="owl-buttons">
                          <div class="owl-prev">prev</div>
                          <div class="owl-next">next</div>
                      </div>
                  </div>
              </div>
          </div>
    </section>
    <!--features carousel end-->

    <section class="panel">
          <header class="panel-heading">
              最新动态
          </header>
          <div class="panel-body">
              <div class="timeline-messages">
                  <!-- Comment -->
                  {% for item in userlog %}
                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{{ item.user.avator_sor.url }}" alt="图片不存在"></a>
                      <div class="message-body {% if forloop.counter|divisibleby:2 %}msg-out{% else %}msg-in{% endif %}">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">{{ item.user.username }}</a>{{ item.create_time }}</p>
                              {% if item.question %}
                              <p>{{ item.operate }}<a href="{% url 'repo:question_detail' item.question.id %}">{{ item.question }}</a></p>
                              {% else %}
                              <p>{{ item.operate }}<a href="{% url 'repo:question_detail' item.answer.question.id %}">{{ item.question }}</a></p>
                              {% endif %}
<!--                              <p>回答了<a href="http://127.0.0.1:8000/question/7679/">sql优化</a></p>-->
                          </div>
                      </div>
                  </div>
                  {% endfor %}

                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{% static 'img/1534407125.png' %}" alt=""></a>
                      <div class="message-body msg-in">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">aaa</a>Aug. 16, 2018, 8:12 a.m.</p>
                              <p>回答了<a href="http://127.0.0.1:8000/question/7574/">手写python：用递归的方式判断字符串是否为回文；</a></p>
                          </div>
                      </div>
                  </div>
                  <!-- /comment -->

                  <!-- Comment -->
                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{% static 'img/1534407125.png' %}" alt=""></a>
                      <div class="message-body msg-out">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">aaa</a>Aug. 16, 2018, 7:01 a.m.</p>
                              <p>回答了<a href="http://127.0.0.1:8000/question/7587/">RESTful架构(SOAP,RPC)</a></p>
                          </div>
                      </div>
                  </div>
                  <!-- /comment -->

                  <!-- Comment -->
                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{% static 'img/1534407125.png' %}" alt=""></a>
                      <div class="message-body msg-in">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">aaa</a>Aug. 16, 2018, 7 a.m.</p>
                              <p>回答了<a href="http://127.0.0.1:8000/question/7576/">三次握手</a></p>
                          </div>
                      </div>
                  </div>
                  <!-- /comment -->

                  <!-- Comment -->
                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{% static 'img/1534407125.png' %}" alt=""></a>
                      <div class="message-body msg-out">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">aaa</a>Aug. 16, 2018, 7 a.m.</p>
                              <p>回答了<a href="http://127.0.0.1:8000/question/7568/">手写：一个长度n的无序数字元素列表，如何求中位数，如何尽快的估算中位数，你的算法复杂度是多少；</a></p>
                          </div>
                      </div>
                  </div>
                  <!-- /comment -->

                  <!-- Comment -->
                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{% static 'img/1534323246.png' %}" alt=""></a>
                      <div class="message-body msg-in">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">admin</a>Aug. 15, 2018, 3:19 a.m.</p>
                              <p>回答了<a href="http://127.0.0.1:8000/question/7585/">XSRF和XSS</a></p>
                          </div>
                      </div>
                  </div>
                  <!-- /comment -->

                  <!-- Comment -->
                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{% static 'img/1534323246.png' %}" alt=""></a>
                      <div class="message-body msg-out">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">admin</a>Aug. 15, 2018, 3:05 a.m.</p>
                              <p>回答了<a href="http://127.0.0.1:8000/question/7572/">手写：一个列表A=[A1，A2，…,An]，要求把列表中所有的组合情况打印出来；</a></p>
                          </div>
                      </div>
                  </div>
                  <!-- /comment -->

                  <!-- Comment -->
                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{% static 'img/1534323246.png' %}" alt=""></a>
                      <div class="message-body msg-in">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">admin</a>Aug. 15, 2018, 2:08 a.m.</p>
                              <p>回答了<a href="http://127.0.0.1:8000/question/7576/">三次握手</a></p>
                          </div>
                      </div>
                  </div>
                  <!-- /comment -->

              </div>
          </div>
    </section>

    <!--最近刷题的同学 start-->
    <section class="panel">
        <header class="panel-heading">
          最近刷题的同学
        </header>
        <div class="panel-body">
            {% for user in recent_user %}
             <div class="task-thumb">
                 <img src="{{ user.avator_sor.url }}" alt="图片不存在">
                 <div class="clearfix"></div>
                 <a href="#">{{ user.username }}</a>
            </div>
            {% endfor %}
        </div>
    </section>
    <!--custom chart end-->
</aside>
<aside class="profile-info col-lg-3">
  <!--follower start-->
  <section class="panel">
      <div class="follower">
          <div class="panel-body">
              <div class="follow-ava">
                  <img src="{{ request.user.avator_sor.url }}" alt="图片不存在">
              </div>
              <h4>{{ request.user.username }}</h4>
              <h4>您已完成 7 道面试题，加油！</h4>
          </div>
      </div>
      <footer class="follower-foot">
          <ul>
              <li>
                  <h4>7/489</h4>
                  <p>刷题量：1 %</p>
              </li>
              <li>
                  <h4>第{{ no }}名</h4>
                  <p>当前排名：1/4</p>
              </li>
          </ul>
      </footer>
  </section>
  <!--follower end-->
  <!--热门题目 start-->
  <section class="panel">
      <div class="panel-body progress-panel">
          <div class="task-progress">
              <h1>热门算法题目</h1>
              <p>答题人数最多的题目</p>
          </div>
      </div>
      <table class="table table-hover personal-task">
          <tbody>
              <tr>
                  <td>1</td>
                  <td>
                      <a href="http://127.0.0.1:8000/question/7679/" title="sql优化">7679. sql优化</a>
                  </td>
                  <td>
                      <span class="label label-info">入门</span>
                  </td>
              </tr>
              <tr>
                  <td>2</td>
                  <td>
                      <a href="http://127.0.0.1:8000/question/7576/" title="三次握手">7576. 三次握手</a>
                  </td>
                  <td>
                      <span class="label label-info">入门</span>
                  </td>
              </tr>
              <tr>
                  <td>3</td>
                  <td>
                      <a href="http://127.0.0.1:8000/question/7567/" title="单向链表如何使用快速排序算法进行排序；">7567. 单向链表如何使...</a>
                  </td>
                  <td>
                          <span class="label label-info">入门</span>
                  </td>
              </tr>
              <tr>
                  <td>4</td>
                  <td>
                      <a href="http://127.0.0.1:8000/question/7584/" title="HTTP和HTTPS">7584. HTTP和HTTPS</a>
                  </td>
                  <td>
                          <span class="label label-info">入门</span>
                  </td>
              </tr>
              <tr>
                  <td>5</td>
                  <td>
                      <a href="http://127.0.0.1:8000/question/7580/" title="Post和Get">7580. Post和Get</a>
                  </td>
                  <td>
                          <span class="label label-info">入门</span>
                  </td>
              </tr>
          </tbody>
      </table>
  </section>
  <!--work progress end-->
  <!--近30天刷题用户排行榜 start-->
  <section class="panel">
      <div class="panel-body progress-panel">
          <div class="task-progress">
              <h1>近30天刷题用户排行榜</h1>
              <p></p>
          </div>
      </div>
      <table class="table table-hover personal-task">
          <tbody>
              <tr>
                  <td>1</td>
                  <td>
                      <a href="">admin</a>
                  </td>
                  <td>
                      <span>1/489</span>
                  </td>
              </tr>
          </tbody>
      </table>
  </section>
  <!--work progress end-->
</aside>
{% endblock %}

question_repo/templates/uc_answer.html
{% extends 'uc_base.html' %}
{% load staticfiles %}
{% block uc_content %}
  <div class="row">
      <div class="col-lg-12">
          <section class="panel">
              <header class="panel-heading">
                  Dynamic Table
              </header>
              <table class="table table-striped border-top" id="sample_1">
              <thead>
              <tr>
                  <th style="width:8px;"><input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" /></th>
                  <th class="hidden-phone">问题</th>
                  <th class="hidden-phone">我的答案</th>
                  <th class="hidden-phone">收藏量</th>
              </tr>
              </thead>
              <tbody>
              {% for answer in my_answers %}
              <tr class="odd gradeX">
                  <td><input type="checkbox" class="checkboxes" value="1" /></td>
                  <td><a href="{% url 'repo:question_detail' answer.question_id %}">{{ answer.question.title }}</a></td>
                  <td>{{ answer.answer }}</td>
                  <td>{{ answer.answers_collection_set.count }}</td>
              </tr>
              {% endfor %}
              </tbody>
              </table>
          </section>
      </div>
  </div>
  <!-- page end-->
{% endblock %}
{% block load_js %}
    <script type="text/javascript" src="{% static 'assets/data-tables/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/data-tables/DT_bootstrap.js '%}"></script>
    <script src="{% static 'js/dynamic-table.js' %}"></script>
{% endblock %}

question_repo/templates/uc_base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
  <aside class="profile-info col-lg-3">
    <div class="panel">
      <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">

        {% url 'uc:profile' as uc_profile %}
        {% url 'uc:change_passwd' as uc_change_passwd %}
        {% url 'uc:answer' as uc_answer %}
        {% url 'uc:collect' as uc_collect %}
        {% url 'uc:contribut' as uc_contribut %}
        {% url 'uc:approval' as uc_approval %}

        <li role="presentation" class="{% if current_url == uc_profile %}active{% endif %}"><a href="{{ uc_profile }}">个人资料</a></li>
        <li role="presentation" class="{% if current_url == uc_change_passwd %}active{% endif %}"><a href="{{ uc_change_passwd }}">修改密码</a></li>
        <li role="presentation" class="{% if current_url == uc_answer %}active{% endif %}"><a href="{{ uc_answer }}">我的回答</a></li>
        <li role="presentation" class="{% if current_url == uc_collect %}active{% endif %}"><a href="{{ uc_collect }}">我的收藏</a></li>
        <li role="presentation" class="{% if current_url == uc_contribut %}active{% endif %}"><a href="{{ uc_contribut }}">我的贡献</a></li>
        {% if perms.repo.can_change_question_status %}
            <li role="presentation" class="{% if current_url == uc_contribut %} active {% endif %}"><a href="{{ uc_approval }}">待审题目</a></li>
        {% endif %}
        </ul>
      </div>
    </div>
  </aside>
  <aside class="profile-info col-lg-9">
      <section>
          <div class="row">
            {% block uc_content %}
              <div class="col-lg-12">
                  <div class="panel">
                      <div class="panel-body">
                          <div class="bio-chart">
                              <input class="knob" data-width="100" data-height="100" data-displayPrevious=true  data-thickness=".2" value="35" data-fgColor="#e06b7d" data-bgColor="#e8e8e8">
                          </div>
                          <div class="bio-desk">
                              <h4 class="red">Envato Website</h4>
                              <p>Started : 15 July</p>
                              <p>Deadline : 15 August</p>
                          </div>
                      </div>
                  </div>
              </div>
            {% endblock %}
          </div>
      </section>

  </aside>
</div>
{% endblock %}
{% block load_js %}
  <script src="{% static 'assets/jquery-knob/js/jquery.knob.js' %}"></script>
  <script>
      //knob
      $(".knob").knob();
  </script>
{% endblock %}